<a href="https://colab.research.google.com/github/25wh1a0548-collab/NASSCOM/blob/main/panda_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")
# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")
# 1.1 Create a Pandas Series named 's1_1'
s1_1 = pd.Series([10, 20, 30, 40, 50])
# 1.2 Create a 3x4 NumPy array with random integers
np_array1_2 = np.random.randint(1, 101, size=(3, 4))
# 1.3 Convert NumPy array into DataFrame
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])
print("Series:")
print(s1_1)
 print("\nNumPy Array:")
 print(np_array1_2)
 print("\nDataFrame:")
  print(df1_3)
  # Task 2: Synthetic Data Generation for Practice
  print("\n--- Task 2: Synthetic Data Generation for Practice ---")
  # Create DataFrame
  df_sales = pd.DataFrame({
  'Date': pd.date_range(start='2023-01-01',end='2023-04-10')[:100],
  'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
  'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
  'Sales': np.random.randint(100, 1001, 100).astype(float),
  'Quantity': np.random.randint(1, 11, 100).astype(float) })
  # Introduce NaN values
  sales_nan_idx = np.random.choice(df_sales.index, 5, replace=False)
  quantity_nan_idx = np.random.choice(df_sales.index, 3, replace=False)
  df_sales.loc[sales_nan_idx, 'Sales'] = np.nan
  df_sales.loc[quantity_nan_idx, 'Quantity'] = np.nan
  print(df_sales.head())
  # Task 3: Indexing and Slicing in DataFrames
  print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
  # 3.1 Select Region and Sales columns
  df3_1 = df_sales[['Region', 'Sales']]
  # 3.2 Select rows where Product is Laptop
  df3_2 = df_sales[df_sales['Product'] == 'Laptop']
  # 3.3 Region is East and Sales > 500
  df3_3 = df_sales[
  (df_sales['Region'] == 'East') &
   (df_sales['Sales'] > 500) ]
   # 3.4 Sales value for first Monitor entry
   monitor_index = df_sales[df_sales['Product'] == 'Monitor'].index[0]
   val3_4 = df_sales.loc[monitor_index, 'Sales']
   print("\ndf3_1:")
   print(df3_1.head())
   print("\ndf3_2:")
   print(df3_2.head())
   print("\ndf3_3:")
   print(df3_3.head())
   print("\nFirst Monitor Sales:", val3_4)
   # Task 4: Data Cleaning (Handling Missing Values)
   print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
   # 4.1 Count missing values
   missing_counts4_1 = df_sales.isnull().sum()
   # 4.2 Fill missing Sales with mean
   df4_2_filled = df_sales.copy()
   sales_mean = df4_2_filled['Sales'].mean()
   df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(sales_mean)
   # 4.3 Drop rows with any missing values
   df4_3_dropped = df_sales.dropna()
   print("\nMissing Values:")
   print(missing_counts4_1)
   print("\nFilled Sales:")
    print(df4_2_filled.head())
    print("\nRows after dropping NaNs:", len(df4_3_dropped))
    # Task 5: Data Manipulation (Columns, Sorting, Grouping)
    print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
    # 5.1 Create Total_Revenue
    df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']
    # 5.2 Sort by Date ascending then Sales descending
    df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False] )
    # 5.3 Group by Region
    df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()
     # 5.4 Group by Product
     df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()
     print("\nDataFrame with Total_Revenue:")
     print(df_sales.head()) print("\nSorted DataFrame:")
     print(df5_2_sorted.head())
     print("\nGrouped by Region:")
     print(df5_3_grouped_region)
     print("\nAverage Sales by Product:")
     print(df5_4_grouped_product)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[94 25  2 64]
 [19 38 37 69]
 [76 73 41  2]]

DataFrame:
    A   B   C   D
0  94  25   2  64
1  19  38  37  69
2  76  73  41   2

--- Task 2: Synthetic Data Generation for Practice ---
        Date Region  Product  Sales  Quantity
0 2023-01-01   East  Monitor  436.0       1.0
1 2023-01-02  South   Laptop  294.0       1.0
2 2023-01-03   West   Laptop  360.0       6.0
3 2023-01-04  South  Monitor  677.0      10.0
4 2023-01-05   East   Laptop  976.0       7.0

--- Task 3: Indexing and Slicing in DataFrames ---

df3_1:
  Region  Sales
0   East  436.0
1  South  294.0
2   West  360.0
3  South  677.0
4   East  976.0

df3_2:
         Date Region Product  Sales  Quantity
1  2023-01-02  South  Laptop  294.0       1.0
2  2023-01-03   West  Laptop  360.0       6.0
4  2023-01-05   East  Laptop  976.0       7.0
5  2023-01-06  South  Laptop  500.0       4.0
11 2023-01-12  South  Laptop  671.0       5.0

df3_3:
         Date Region   Product  Sales  Quantity
4  2023-01-05   East    Laptop  976.0       7.0
6  2023-01-07   East     Mouse  907.0       1.0
23 2023-01-24   East   Monitor  995.0       5.0
47 2023-02-17   East  Keyboard  744.0       NaN
50 2023-02-20   East   Monitor  865.0       7.0

First Monitor Sales: 436.0

--- Task 4: Data Cleaning (Handling Missing Values) ---

Missing Values:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

Filled Sales:
        Date Region  Product  Sales  Quantity
0 2023-01-01   East  Monitor  436.0       1.0
1 2023-01-02  South   Laptop  294.0       1.0
2 2023-01-03   West   Laptop  360.0       6.0
3 2023-01-04  South  Monitor  677.0      10.0
4 2023-01-05   East   Laptop  976.0       7.0

Rows after dropping NaNs: 92

--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---

DataFrame with Total_Revenue:
        Date Region  Product  Sales  Quantity  Total_Revenue
0 2023-01-01   East  Monitor  436.0       1.0          436.0
1 2023-01-02  South   Laptop  294.0       1.0          294.0
2 2023-01-03   West   Laptop  360.0       6.0         2160.0
3 2023-01-04  South  Monitor  677.0      10.0         6770.0
4 2023-01-05   East   Laptop  976.0       7.0         6832.0

Sorted DataFrame:
        Date Region  Product  Sales  Quantity  Total_Revenue
0 2023-01-01   East  Monitor  436.0       1.0          436.0
1 2023-01-02  South   Laptop  294.0       1.0          294.0
2 2023-01-03   West   Laptop  360.0       6.0         2160.0
3 2023-01-04  South  Monitor  677.0      10.0         6770.0
4 2023-01-05   East   Laptop  976.0       7.0         6832.0

Grouped by Region:
          Sales  Quantity
Region
East    11813.0     132.0
North   13045.0      92.0
South   14481.0     180.0
West    12115.0     114.0

Average Sales by Product:
Product
Keyboard    547.423077
Laptop      551.590909
Monitor     538.464286
Mouse       526.789474
Name: Sales, dtype: float64



